version: '3.1'
services:
  mysql:
    image: mysql:5.6
    platform: linux/amd64
    ports:
      - '3306:3306'
    volumes:
      - .docker/mysql/schema:/docker-entrypoint-initdb.d:delegated
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=US/Central

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  app:
    image: node:16
    working_dir: /app
    ports:
      - '4008:4008'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - AWS_XRAY_LOG_LEVEL=silent
      - AWS_XRAY_CONTEXT_MISSING=LOG_ERROR
    command: "bash -c 'cd /app && npm run start:dev'"
    depends_on:
      - mysql
