version: '3.1'
services:
  localstack:
    image: localstack/localstack@sha256:82c31d48e5de12357ede5656dc8b115026f487694d9b6ba358521f3529c33122
    env_file:
      - .docker/local.env
    ports:
      - '4566:4566'
      - '8081:8081'
    volumes:
      - ./.docker/localstack:/docker-entrypoint-initaws.d
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8081
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack
  mysql:
    image: mysql:5.7@sha256:f57eef421000aaf8332a91ab0b6c96b3c83ed2a981c29e6528b21ce10197cd16
    platform: linux/amd64
    ports:
      - '3306:3306'
    volumes:
      - .docker/mysql/schema:/docker-entrypoint-initdb.d:delegated
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=US/Central

  redis:
    image: redis:latest@sha256:93a5ed8cdfa909a12cb41e5605c147756b804a9fe38376f8afed133f427ea828
    ports:
      - '6379:6379'

  app:
    image: node:18@sha256:d9946ebbeb3ca08ccaa24a8220d7da1f9e9fd749d489913faeed89e02f70a202
    working_dir: /app
    ports:
      - '4008:4008'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - AWS_XRAY_LOG_LEVEL=silent
      - AWS_XRAY_CONTEXT_MISSING=LOG_ERROR
    command: "bash -c 'cd /app && npm run start:dev'"
    depends_on:
      - mysql
